version: "3"

services:
  jupyter-pytorch:
    image: jupyter-pytorch
    build:
      context: ./
      dockerfile: jupyter-pytorch.Dockerfile
    ipc: host
    ulimits:
      stack: 67108864
      memlock: -1
    ports:
      - ${JUPYTER_PORT}:${JUPYTER_PORT}
    volumes:
      - .:/workspace/project
    command:
      [
        "jupyter",
        "lab",
        "--ip=*",
        "--port=${JUPYTER_PORT}",
        "--allow-root",
        "--notebook-dir=/workspace",
        "--NotebookApp.token=''",
        "--NotebookApp.password=''"
      ]

  tensorboard:
    image: nvcr.io/nvidia/tensorflow:22.08-tf2-py3
    ipc: host
    shm_size: "1g"
    ulimits:
      memlock: -1
    ports:
      - ${TENSORBOARD_PORT}:${TENSORBOARD_PORT}
    volumes:
      - .:/jupyter
    command:
      [
        "tensorboard",
        "--logdir=${TENSORBOARD_DIR}",
        "--port=${TENSORBOARD_PORT}",
        "--bind_all",
      ]

